### ISSUE TITLE
3.7 to 3.10 redo action is missing

### ISSUE THREAD

**Issue by sinedie** [plrenaudin/svelte-storez#11]
I just notice that on the _codesandbox_ on the _readme_ you can redo an action with using `storez v0.3.7` but when changing to `v0.3.10`, it is gone.

I was about to create a pull request to solve #9  but find out this. I could implementing too, but idk, seems that it was working

**Comment by plrenaudin** [comment]
Thanks for raising this! 

It is a real mystery for me, why did the redo option disappear between those 2 versions?? I couldn't find the reason by diving into the git logs... I ended up bringing it back from npm package history :man_shrugging: `0.3.12` should have it now
